# Generated by Django 4.0.4 on 2022-06-01 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consultant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
                ('can_login', models.IntegerField(default=1)),
                ('login_success_msg', models.CharField(blank=True, max_length=255, null=True)),
                ('login_failure_msg', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LogEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_datetime', models.DateTimeField()),
                ('token', models.CharField(max_length=1000)),
                ('email', models.CharField(max_length=255)),
                ('event_type', models.CharField(max_length=100)),
                ('log_event_descr', models.CharField(max_length=1000)),
            ],
        ),
    ]
